install mod_plate automatically, if possible
Taving to remember to run apxs_install is annoying. This adds it to make
install, but prints out a warning and move on if it fails (this is because
apache's default install dir isn't user-writeable and doesn't obey prefix,
so it'll fail unless you explicitly change it)

diff --git a/src/vw/Plate/Makefile.am b/src/vw/Plate/Makefile.am
--- a/src/vw/Plate/Makefile.am
+++ b/src/vw/Plate/Makefile.am
@@ -58,6 +58,18 @@ mod_plate_la_LIBADD = $(PLATE_LOCAL_LIBS)
 mod_plate_la_LDFLAGS = @APXS_LDFLAGS@ -module -rpath $(APXS_INSTALLDIR) -avoid-version
 noinst_LTLIBRARIES = mod_plate.la
 
+install-exec-local:
+	@if ! $(LIBTOOL) --mode=install cp mod_plate.la $(APXS_INSTALLDIR); then\
+		echo "********************************************************************************";\
+		echo "*                                                                              *";\
+		echo "*                                                                              *";\
+		echo "*                    WARNING: Failed to install mod_plate!                     *";\
+		echo "*                                                                              *";\
+		echo "*                                                                              *";\
+		echo "********************************************************************************";\
+	fi
+	rm -f $(APXS_INSTALLDIR)/mod_plate.la
+
 apxs_install: mod_plate.la
 	$(LIBTOOL) --mode=install cp mod_plate.la $(APXS_INSTALLDIR)
 	rm -f $(APXS_INSTALLDIR)/mod_plate.la
